package com.fabiofpaulo.todolist.utils

import com.fabiofpaulo.todolist.enums.TodoPriority
import com.fabiofpaulo.todolist.enums.TodoStatus
import com.fabiofpaulo.todolist.models.Todo

fun generateRandomTodos(count: Int): List<Todo> {
    val sampleLabels = listOf(
        "Buy groceries",
        "Finish report",
        "Clean room",
        "Go for a run",
        "Reply to emails",
        "Read a book",
        "Fix the bike",
        "Call mom",
        "Plan weekend",
        "Water plants",
        "Update resume",
        "Book dentist",
        "Pay bills",
        "Backup laptop",
        "Organize desk",
        "Wash car",
        "Schedule meeting",
        "Walk the dog",
        "Practice guitar",
        "Sort laundry",
        "Meditate",
        "Take out trash",
        "Grocery shopping",
        "Write journal",
        "Clean kitchen",
        "Meal prep",
        "Check news",
        "Listen to podcast",
        "Do yoga",
        "Stretch body",
        "Study Kotlin",
        "Learn design patterns",
        "Review pull requests",
        "Update LinkedIn",
        "Clean inbox",
        "Organize bookmarks",
        "Check weather",
        "Research vacation spots",
        "Buy gift",
        "Write blog post",
        "Refactor code",
        "Sketch UI ideas",
        "Update calendar",
        "Fix plumbing",
        "Paint wall",
        "Install updates",
        "Declutter shelf",
        "Test app feature",
        "Run unit tests",
        "Read tech article",
        "Send invoice",
        "Design logo",
        "Brainstorm app ideas",
        "Refill water bottle",
        "Optimize code",
        "Create presentation",
        "Check bank account",
        "Donate clothes",
        "Fix bike tire",
        "Print documents",
        "Water garden",
        "Review finances",
        "Plan birthday",
        "Sort photos",
        "Clean bathroom",
        "Learn Spanish",
        "Try new recipe",
        "Set goals",
        "Check stocks",
        "Schedule haircut",
        "Renew subscription",
        "Organize files",
        "Plan trip",
        "Recharge devices",
        "Build Lego set",
        "Read fiction",
        "Inspect code",
        "Polish shoes",
        "Update portfolio",
        "Study math",
        "Sketch character",
        "Do dishes",
        "Change sheets",
        "Watch tutorial",
        "Dust shelves",
        "Tidy wardrobe",
        "Sync phone",
        "Visit grandma",
        "Review project",
        "Call doctor",
        "Feed pets",
        "Update software",
        "Buy batteries",
        "Send thank-you note",
        "Clean fridge",
        "Review notes",
        "Check tire pressure",
        "Post on social media",
        "Apply for job",
        "Create task list",
        "Check calendar",
        "Stretch legs"
    )

    return List(count) {
        Todo(
            label = sampleLabels.random(),
            status = TodoStatus.entries.toTypedArray().random(),
            priority = TodoPriority.entries.toTypedArray().random()
        )
    }
}

fun createEmptyTodo() = Todo(
    label = "",
    status = TodoStatus.PENDING,
    priority = TodoPriority.LOW
)